# -*- coding: utf-8 -*-
#############################################################################
#
#    Partenaires Succes.
#
#    Copyright (C) 2025-TODAY Partenaire Succes(<https://www.partenairesucces.com/>)
#    Author: Adama KONE
#
#############################################################################
{
    'name': 'Personnalisation du Module Inventaire',
    'category': 'Stock',
    'summary': """Customisation de Inventaire pour Odoo 18.0""",
    'description': """Adaptation du module Inventaire pour répondre aux besoins 
        spécifiques des utilisateurs d'Odoo 19.0.""",
    'author': 'Adams KONE',
    'company': 'Partenaires Succes',
    'maintainer': 'Adams KONE',
    'website': "https://www.partenairesucces.com/",
    'depends': [
        'base',
        'stock',
        'stock_account',
        'product',
        'sale',
        'purchase',
        'hr',
        'custom_pos',
        'account',
        'point_of_sale',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/avco_guard_cron.xml',
        'security/product_security.xml',
        'security/stock_picking_inter_security.xml',
        'data/code_category_inventory_data.xml',
        'data/data_sequence.xml',
        'data/product_pricelist_data.xml',
        'views/stock_move_views.xml',
        'views/product_template_views.xml',
        'views/teams_inventory_views.xml',
        'views/res_company_views.xml',
        'views/code_inventory_views.xml',
        'views/physical_inventory_views.xml',
        'views/family_inventory_views.xml',
        'views/radius_inventory_views.xml',
        'views/category_gestion_x3_views.xml',
        'report/report_template_physical_inventory.xml',
        'report/report_inventaire_decompte_template.xml',
        'report/report_fiche_comptage_template.xml',
        'report/report_bon_reception_template.xml',
        'report/report_retours_receptions_template.xml',
        'report/report.xml',
        'wizard/product_select_wizard_views.xml',
        'views/picking_inter_company_views.xml',
        'views/sale_order_views.xml',
        'views/stock_warehouse_orderpoint_view.xml',
        'views/purchase_order_views.xml',
        'views/stock_scrap_breakers_views.xml',
        'views/picking_request_company_views.xml',
        'views/stock_product_multicompany_views.xml',
        'views/account_views.xml',
        'views/company_status_views.xml',
        'views/sortie_entrant_menu_views.xml',
        'wizard/reception_directe_wizard_views.xml',
        'wizard/retour_carton_wizard_views.xml',
        'wizard/retour_inventaire_wizard_views.xml',
        'wizard/retour_fournisseur_wizard_views.xml',
        'wizard/rapport_retours_receptions_wizard_views.xml',
        'wizard/reception_correction_info_wizard_views.xml',
        'wizard/fiche_comptage_wizard_views.xml',
        'wizard/stock_picking_return_views.xml',
        'views/physical_inventory_retour_views.xml',
        'views/pos_session_views.xml',
        'views/fournisseur_shortcuts_views.xml',
        'views/physical_inventory_archive.xml',
        'views/stock_avco_report_views.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
