{
    'name': 'Personnalisation des rapports PDF',
    'summary': 'Summery',
    'description': 'Le module permet de personnaliser les rapports PDF',
    'category': 'Sales/account',
    'author': 'Alexandre Koua, Adama KONE',
    'company': 'Partenaires Succes',
    'maintainer': 'Alexandre Koua',
    'website': "https://www.partenairesucces.com/",
    'license': 'AGPL-3',
    'depends': [
        'product',
        'stock',
        'stock_account',
        'purchase',
        'custom_stock',
        'custom_sales',
        'custom_pos',
        'dashboard_management_administration',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'wizard/stock_valorise_report_wizard_views.xml',
        'report/stock_picking_report_template.xml',
        'wizard/sale_stat_report_wizard_view.xml',
        'report/report_sale_stat_template.xml',
        'wizard/reception_fournisseur_wizard_views.xml',
        'report/report_reception_fournisseur_template.xml',
        'wizard/suplier_report_return_wizard.xml',
        'report/report_suplier_return_template.xml',
        'wizard/cumul_inventary_report_wizard.xml',
        'report/report_cumul_inventary_template.xml',
        'wizard/stock_adjustment_report_wizard.xml',
        'report/report_stock_scrap_template.xml',
        'wizard/stock_casse_report_wizard.xml',
        'report/report_casse_template.xml',
        'wizard/report_daily_sales_wizard_view.xml',
        'report/report_daily_sales_template.xml',
        'report/report_cadencier_template.xml',
        'wizard/cadencier_sale_view.xml',
        'report/report_catalog_template.xml',
        'wizard/catalog_product_report_wizard.xml',
        'wizard/retours_consolides_report_wizard_views.xml',
        'report/report_retours_consolides_template.xml',

        'report/recap_caisses_report.xml',
        'report/recap_caisses_template.xml',
        'wizard/recap_caisses_wizard_views.xml',
        'wizard/stock_product_report_wizard_view.xml',
        'wizard/achat_produit_report_wizard_views.xml',
        'report/report_achat_produit_template.xml',
        'wizard/sale_vte_x3_report_wizard_views.xml',
        'report/report_sale_vte_x3_template.xml',
        'wizard/stock_movement_report_wizard_views.xml',
        'report/report_stock_movement_template.xml',
        # 'wizard/livraison_report_wizard_views.xml',
        # 'report/report_livraison_template.xml',
    ],
    'installable': True,
    'auto_install': False
}
